const constants = {
  SAVE: 'SAVE',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',

  CHANGE_MODE: 'CHANGE_MODE',
  CONTENT_CHANGE: 'CONTENT_CHANGE',
  TOGGLE_LEFT_NAV: 'TOGGLE_LEFT_NAV',
  CLOSE_LEFT_NAV: 'CLOSE_LEFT_NAV',
  OPEN_LEFT_NAV: 'OPEN_LEFT_NAV',
  //fullscreen
  TOGGLE_FULLSCREEN: 'TOGGLE_FULLSCREEN',
  //overview
  REINSERT: 'REINSERT',
  SELECT_SLIDE: 'SELECT_SLIDE',
  ADD_SLIDE: 'ADD_SLIDE',
  REMOVE_SLIDE: 'REMOVE_SLIDE',
  SLIDE: {
    NEXT: 'SLIDE.NEXT',
    PRE: 'SLIDE.PRE',
  },

  //messages
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',


  MODE: {
    MARKDOWN: 'markdown',
    PRESENTATION: 'presentation',
    FULLSCREEN: 'fullscreen',
  },
};
export default constants;
