const constants = {
  CHANGE_MODE: 'CHANGE_MODE',
  CONTENT_CHANGE: 'CONTENT_CHANGE',
  TOGGLE_LEFT_NAV: 'TOGGLE_LEFT_NAV',
  CLOSE_LEFT_NAV: 'CLOSE_LEFT_NAV',
  OPEN_LEFT_NAV: 'OPEN_LEFT_NAV',
  REINSERT: 'REINSERT',
  SLIDE: {
    NEXT: 'SLIDE.NEXT',
    PRE: 'SLIDE.PRE',
  },
};
export default constants;
